### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by mbuesch** [wjakobczyk/st7920#10]
Dear Maintainer,

there has not been any activity for many months.
Is this project still alive?

**Comment by wjakobczyk** [comment]
I no longer have hardware to test this, so can't really maintain it actively TBH.

**Comment by mbuesch** [comment]
Hi,

thanks a lot for your quick reply.
I would like to offer my help to maintain this project.
I do have hardware and I actually plan to acquire at least one more for the purpose of maintenance.

I do have a change for embedded-hal 1 (stable) pending. I'll submit that after #8 is resolved.

I think this project doesn't need many changes. And I actually don't currently plan to do more changes, yet.
However, I am willing to help keep this project alive and up to date with the occasional maintenance change.

Michael.

**Comment by wjakobczyk** [comment]
Ok, sounds good, thanks for the help.

**Comment by mbuesch** [comment]
Thanks :)
