### ISSUE TITLE
publish 0.3 at crates.io

### ISSUE THREAD

**Issue by Alexander89** [wjakobczyk/st7920#5]
hi, 

it would be great if you could publish the current master to crates.io

**Comment by wjakobczyk** [comment]
I currently don't have hardware to test, at hand. Have you tested those changes well? :)

**Comment by mbuesch** [comment]
I tested this (together with #6 applied) and it seems to work fine. The set_pixel method correctly draws pixels.

Therefore, I'd suggest to publish 0.3 and possibly also publish an alpha version with #6 applied.

**Comment by wjakobczyk** [comment]
I've published as suggested, thanks!
